name: Foresight CI Workflow Flaky


on:
  workflow_dispatch:


#env:
  #FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  #WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go:
        - '1.16'

    steps:
    - uses: actions/checkout@v3

    
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
        

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - run: go version
    - name: Set up gotestsum
      run: |
        go install gotest.tools/gotestsum@latest
    - name: Go Test
      run: |
        cd hello
        gotestsum --hide-summary=all --format standard-verbose --jsonfile results.json --rerun-fails=5
    - name: Analyze Test and/or Coverage Results
      if: always()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.FORESIGHT_API_KEY }}
        test_framework: GOLANG
        test_format: JSON
        test_path: ./hello/results.json
